### ISSUE TITLE
Unable to use the 'boot_command' with the vsphere-iso plugin

### ISSUE THREAD

**Issue by mmd1999** [jetbrains-infra/packer-builder-vsphere#120]
Hi,
I'm struggling a bit with how to use the boot_command with the vsphere-iso plugin.  I can build fine if I leave the parameter out and type in the commands manually but obviously not ideal.  Any pointers into something I may be doing wrong are much appreciated.  I've attached a copy of the builder file I'm using to provision a template.  If there's any information that I missed that would be helpful, please let me know.  Thanks!

Some variations of the boot_command that I've tried to test if only certain keys were failing:
"boot_command": [
  "\<return\>"
]
"boot_command": [
  "\<enter\>"
]
"boot_command": [
  "\<tab\>"
]
"boot_command": [
  "\<tab\> text ks=http://10.1.1.2:80/ks.cfg\<enter\>\<wait\>"
]

ISO's attempted:
CentOS-7-x86_64-DVD-1804.iso
ubuntu-16.04.4-server-amd64.iso

Attempted adjusting the PACKER_KEY_INTERVAL environment variable
PACKER_KEY_INTERVAL=200ms
PACKER_KEY_INTERVAL=10ms

Here's some info on my environment/what I'm currently using:
vCenter version: 6.5.0 build 8024368
packer-builder-vsphere-iso.linux version: 2.0
packer version: 1.2.4
packer build server: CentOS Linux release 7.5.1804 (Core)

The error I receive when I attempt to build a template:
vsphere-iso output will be in this color.

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Adding CD-ROM drives...
==> vsphere-iso: Set boot order...
==> vsphere-iso: Power on VM...
==> vsphere-iso: Waiting 15s for boot...
==> vsphere-iso: Typing boot command...
==> vsphere-iso: Power off VM...
==> vsphere-iso: Destroying VM...
Build 'vsphere-iso' errored: error typing a boot command: ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: error typing a boot command: ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.

==> Builds finished but no artifacts were created.

[centos7-packer.txt](https://github.com/jetbrains-infra/packer-builder-vsphere/files/2085476/centos7-packer.txt)

**Comment by kempy007** [comment]
Bump, same issue here however my VM will crash and deadlock (which I have to forcefully kill on the esxi host before I can remove it from inventory), was trying to invoke the API directly to triage.  v6.5.0, 7967591

**Comment by mmd1999** [comment]
Hi @kempy007, I have seen that issue as well on my end.  I decided to try slip-streaming my kickstart file into the ISO so I didn't have to deal with it but it'll get a couple minutes into the build then hang (can't powerOff, reset, etc).

**Comment by kempy007** [comment]
I had the error on this opening thread, when the esxi host was not 6.5 but vcenter was 6.5. 
```ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.```

_**But it looks like it's actually running the install at 15mhz after the boot_cmd was entered (was running full speed prior to this), which is taking a very long time (should be 4mins)**_ 

So I switched up to packer 1.2.4 and it no longer locks after entering the boot_cmd.
Which works fine by hand (full speed) if I take over the console and remove the boot_cmd line before starting job/task .  

Trying to backport build process to RHEL6 which does not look for ks.cfg on 2nd cdrom.

Re: slipstreaming iso; Was trying to avoid having to rebuild the boot code (vmlinuz) to look for the ks.cfg, if you have an easy method I'm all ears.

**Comment by kempy007** [comment]
unable to download latest beta, it redirects to version 2.0 of the plugin which I have been using.

**Comment by mmd1999** [comment]
ahhh, I was wondering about that.  We are still on 6.0 for our ESXi hosts so that explains that issue :)

We're currently using packer 1.2.4 and seeing the lock issues, although maybe having the older ESXi version is contributing to that too.

here's what I did for CentOS 7 if you're using that, it wasn't too difficult actually.  I mostly followed the instructions on this thread and threw it in a shell script (attached).  https://serverfault.com/questions/517908/how-to-create-a-custom-iso-image-in-centos  Not sure how applicable it is to version 6 though.
[build_custom_ISO.txt](https://github.com/jetbrains-infra/packer-builder-vsphere/files/2091086/build_custom_ISO.txt)

**Comment by xenithorb** [comment]
Though unrelated to OP's original issue, the deadlock issue is probably due to the plugin accidentally setting the CPULimit to 0MHz which basically halts the system. (Unlimited by default)

See more here for a workaround for the "lock issue":  https://github.com/jetbrains-infra/packer-builder-vsphere/issues/119#issuecomment-397048991

**Comment by kempy007** [comment]
I was unable to replicate this in my lab environment today. thus unable to validate the workaround today. 
so I'm just popping some notes here! 
I suspect the esxi version is older where I had the problem.

Vsphere Version 6.5.0.10000 Build 5973321
VMware ESXi, 6.5.0, 8294253 
Packer 1.2.3
 File: packer.exe
CRC-32: 4aaf2628
   MD4: b26d96cf79e9f023385e356788709258
   MD5: f869d42152ae15bdf9f015bedccb5fcc
 SHA-1: e14f7d563ad06ad4ca372ede95fcad7b02926553

version2.0 
 File: packer-builder-vsphere-iso.exe
CRC-32: 141b6b49
   MD4: 6acc79fabd8772f39180de2e0a721b36
   MD5: 9b6f2163b1d5ee948569bd9e20415e20
 SHA-1: 1240322a236bdfe468fe13b36f5b90415f72bcad

== no issue with boot command and 0-30mhz


Vsphere Version 6.5.0.10000 Build 5973321
VMware ESXi, 6.5.0, 8294253 
Packer 1.2.4
File: packer.exe
CRC-32: e6949a40
   MD4: 3c1ab125a9a3d75fa923da5813295432
   MD5: f5efb95b7a004822c3b91e29fe35c9d3
 SHA-1: 058661cb16ef7eeaae69594ab76aa015cec8e060
 
version2.0 
 File: packer-builder-vsphere-iso.exe
CRC-32: 141b6b49
   MD4: 6acc79fabd8772f39180de2e0a721b36
   MD5: 9b6f2163b1d5ee948569bd9e20415e20
 SHA-1: 1240322a236bdfe468fe13b36f5b90415f72bcad
 
== no issue with boot command and 0-30mhz
 
 
 
For Reference;
 File: packer-builder-vsphere-iso.exev2.0b4
CRC-32: 7daa3213
   MD4: d9a9e40b7099e0fcc5201d58febea7c0
   MD5: d2ccb52321de2a3f3923792cb482b970
 SHA-1: 49e3571a9ea3cb5e5c89306d6dfdc1d9e3a36776

 File: packer-builder-vsphere-iso.exe.v2.0
CRC-32: 141b6b49
   MD4: 6acc79fabd8772f39180de2e0a721b36
   MD5: 9b6f2163b1d5ee948569bd9e20415e20
 SHA-1: 1240322a236bdfe468fe13b36f5b90415f72bcad
 
  File: packer-builder-vsphere-iso.exe.v1.6
CRC-32: 36509eb8
   MD4: fda4ab976cd597b7dd218d3fe70b7588
   MD5: c8a681d96de0390f06abcfb6a17d1c60
 SHA-1: 52df0fb0d982fa5c4cc1208a71525c30c386055f




{
 "variables": 
 {
  "_comment": "see readme.txt"
 },
 
 "builders": [{
  "name": "vm-build-test1",
  "type": "vsphere-iso",

  "vcenter_server": "192.168.100.201",
  "insecure_connection": "true",
  "username": "adminreallyisatrator@cloud01.local",
  "password": "itsapassword",
  "datacenter": "Cloud01",
  "cluster": "Cluster01",
  
  "disk_size": 20000,
  
  "shutdown_command": "echo 'shutdown -P now' > shutdown.sh; echo 'itsapassword'|sudo -S sh 'shutdown.sh'",
  "boot_command": "<tab> text ks=cdrom:/ks.cfg<enter><wait>",
	
  "iso_paths": "[Lun0]/rhel-server-7.4-x86_64-dvd.iso,[Lun0]/kickstart.iso", 
  
  "communicator": "ssh",
  "ssh_username": "admin",
  "ssh_password": "itsapassword",
  "ssh_port": 22,

  "vm_name": "vm-build-test1",
  "guest_os_type": "otherGuest",
  "convert_to_template": "false",

  "datastore": "Lun2",
  "disk_thin_provisioned": "true",
  "CPUs": "1", 
  "ram": "512", 
  "network": "VM Network"
  }] 
}

**Comment by kempy007** [comment]
==ok (lab)
Vsphere Version 6.5.0.10000 Build 5973321
VMware ESXi, 6.5.0, 8294253

==issue
vsphere Version 6.5.0.20000 Build 8667236 (newer than lab)
VMware ESXi, 6.5.0, 7967591 (older than lab)

Packer v1.2.4 (same as lab)
  File: packer.exe
CRC-32: e6949a40
   MD4: 3c1ab125a9a3d75fa923da5813295432
   MD5: f5efb95b7a004822c3b91e29fe35c9d3
 SHA-1: 058661cb16ef7eeaae69594ab76aa015cec8e060

version 2.0 (same as lab)
File: packer-builder-vsphere-iso.exe
CRC-32: 141b6b49
   MD4: 6acc79fabd8772f39180de2e0a721b36
   MD5: 9b6f2163b1d5ee948569bd9e20415e20
 SHA-1: 1240322a236bdfe468fe13b36f5b90415f72bcad

Ok with ```"CPU_limit": -1,``` 

I suspect the issue is fixed in the later esxi image.

Can we update the readme.md to add in a recommendation to have this value set?

**Comment by mmd1999** [comment]
I don't yet have an ESXi v6.5 host to try against but I imaging once I do, the boot command issue will go away.  the "CPU_limit" workaround works for my VM deadlock issue as well.

**Comment by casz** [comment]
We updated everything to VMware ESXi, 6.5.0, 8294253 Also running vSphere Client version 6.5.0.20000

And everything is working flawlessly 👍

**Comment by mmd1999** [comment]
Thanks @casz !  We still don't have any 6.5 hosts to work with but it seems like I can safely assume that's where my issue lies.  I'll go ahead and close this case.  Appreciate everyone's input!
